[
	{"id":1, "pergunta"  : "Depois de saber o que deve fazer para atingir o objetivo, quando o cliente deve iniciar o planejamento?",
	 "respostas" : [{"A":"Ainda hoje"}, {"B":"1 semana antes do objetivo"}],
	 "correta"   : "A"},
	{"id":2, "pergunta"  : "Qual a melhor forma de garantir que o cliente virá para a consultoria?",
	 "respostas" : [{"A":"Ligação de vantagem antes da consultoria"}, {"B":"Torcer com entusiasmo para que ele venha"}],
	 "correta"   : "A"},
	{"id":3, "pergunta"  : "Por que perguntar as expectativas do cliente no começo da consultoria?",
	 "respostas" : [{"A":"Para anotar no papel e o layot ficar mais bonito"}, {"B":"Para alinhar sua apresentação com a expectativa e garantir que ele saia satisfeito"}],
	 "correta"   : "B"},
	{"id":4, "pergunta"  : "Quais as vantagens da W1 para relembrar na consultoria?",
	 "respostas" : [{"A":"Investimento pesado em Marketing"}, {"B":"Horários flexíveis, sem produto próprio, ver a vida em todas as áreas"}],
	 "correta"   : "B"},
	{"id":5, "pergunta"  : "Por que apresentar novamente o ABS?",
	 "respostas" : [{"A":"Para reforçar com o cliente que é uma data de decisão"}, {"B":"Para a consultoria demorar mais"}],
	 "correta"   : "A"},
	{"id":6, "pergunta"  : "Qual a base para uma construção sólida da vida financeira do cliente?",
	 "respostas" : [{"A":"Consumismo e apostas em loterias"}, {"B":"Educação Financeira e Proteção de Patrimônio"}],
	 "correta"   : "B"},
	{"id":7, "pergunta"  : "Quando deve-se usar técnicas de fechamento?",
	 "respostas" : [{"A":"Quando você sabe que aquela decisão é importante para seu cliente e ele não está 100% seguro"}, {"B":"A todo instante"}],
	 "correta"   : "A"},
	{"id":8, "pergunta"  : "Quais as características de um bom investimento para reserva de emergência?",
	 "respostas" : [{"A":"Rentabilidade acima do CDI com alta volatilidade"}, {"B":"Liquidez diária e baixa volatilidade"}],
	 "correta"   : "B"},
	{"id":9, "pergunta"  : "Em qual título do tesouro o cliente não terá risco de desvalorização do título?",
	 "respostas" : [{"A":"Tesouro SELIC (LFT)"}, {"B":"Apenas no pré-fixado para 2021"}],
	 "correta"   : "B"},
	{"id":10, "pergunta"  : "Qual deve ser seu objetivo em cada consultoria que faz?",
	 "respostas" : [{"A":"Maximizar o meu ganho e os PPs"}, {"B":"Ajudar meu cliente a conquistar seus objetivos como se fosse alguém muito querido por mim"}],
	 "correta"   : "B"}
	 ]